const products = [
	{ name: 'milk', category: 'dairy', isFood: true },
	{ name: 'loaf', category: 'bread', isFood: true },
	{ name: 'car', category: 'toys', isFood: false },
	{ name: 'doll', category: 'toys', isFood: false },
	{ name: 'pipe', category: 'construction', isFood: false },
	{ name: 'hammer', category: 'construction', isFood: false },
	{ name: 'cheese', category: 'dairy', isFood: true },
	{ name: 'apple', category: 'fruits', isFood: true },
	{ name: 'banana', category: 'fruits', isFood: true },
	{ name: 'weed', category: 'contraband', isFood: false },
	{ name: 'steroids', category: 'contraband', isFood: false },
	{ name: 'orange', category: 'fruits', isFood: true },
	{ name: 'carrot', category: 'vegetables', isFood: true },
	{ name: 'cucumber', category: 'vegetables', isFood: true },
	{ name: 'pepsi', category: 'drinks', isFood: true },
	{ name: 'coke', category: 'drinks', isFood: true },
	{ name: 'chips', category: 'snacks', isFood: true },
	{ name: 'chocolate', category: 'sweets', isFood: true },
	{ name: 'soap', category: 'hygiene', isFood: false },
	{ name: 'toothpaste', category: 'hygiene', isFood: false },
	{ name: 'tank', category: 'other', isFood: false },
	{ name: 'pistol', category: 'other', isFood: false },
	{ name: 'rocket', category: 'other', isFood: false },
	{ name: 'grenade', category: 'other', isFood: false },
];

export default products;
